stages:
  - test

services:
  - name: postgres:13
    alias: postgres
    command: ["postgres", "-c", "log_statement=all"]

variables:
  POSTGRES_DB: student
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

test:
  image: maven:3.8.1-jdk-11
  before_script:
    - apt-get update && apt-get install -y postgresql-client git time
    - echo "Waiting for PostgreSQL to be ready..."
    - until PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1;" &>/dev/null; do sleep 2; done
    - echo "PostgreSQL is ready!"
    - mkdir -p logs  # Ensure logs directory exists
  script:
    - echo "Fetching last 5 commits..."
    - git fetch --all
    - git log --pretty=format:'%h - %s' -n 5 > logs/commit_history.log  # Store last 5 commits
    - echo "Processing last 5 commits..."
    - |
      for commit_hash in $(git log --format='%H' -n 5); do
        commit_message=$(git log --format='%s' -n 1 $commit_hash)
        echo "Processing commit $commit_hash: $commit_message" | tee -a logs/resource_usage.log
        git checkout $commit_hash
        echo "Running tests for commit $commit_hash..." | tee -a logs/resource_usage.log
        # Run the time command to measure resource usage of the tests
        { /usr/bin/time -v mvn clean test; } 2>&1 | tee -a logs/resource_usage.log
      done
  artifacts:
    paths:
      - logs/
    expire_in: 1 week
