stages:
  - test

services:
  - name: postgres:13
    alias: postgres
    command: ["postgres", "-c", "log_statement=all"]

variables:
  POSTGRES_DB: student
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

test:
  image: maven:3.8.1-jdk-11
  before_script:
    - apt-get update && apt-get install -y postgresql-client git
    - echo "Waiting for PostgreSQL to be ready..."
    - until PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1;" &>/dev/null; do sleep 2; done
    - echo "PostgreSQL is ready!"
    - mkdir -p logs  # Ensure logs directory exists
  script:
    - echo "Fetching last 15 commits..."
    - git fetch --all
    - git log --pretty=format:'%h - %s' -n 15 > logs/commit_history.log  # Store last 15 commits
    - echo "Processing last 5 commits..."
    - for commit in $(git rev-list --max-count=15 HEAD); do
        echo "Checking out commit $commit...";
        git checkout $commit;
        echo "Restoring exact state of tests for commit $commit...";
        mvn clean test | tee -a logs/full_test_logs.log | grep -E "Initial CPU usage|Final CPU usage|Memory used" >> logs/resource_usage.log;
      done
  artifacts:
    paths:
      - logs/
    expire_in: 1 week
