stages:
  - build_joular
 

# Stage to clone and build the JoularJX agent
build_joular:
  stage: build_joular
  image: maven:3.8.1-jdk-11
  script:
    - echo "Cloning JoularJX repository..."
    - git clone https://github.com/joular/joularjx.git
    - cd joularjx/
    - echo "Building JoularJX agent..."
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - joularjx/target/joularjx.jar
    expire_in: 1 week
