stages:
  - build_joular
  - build_and_run

variables:
  POSTGRES_DB: student
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

services:
  - name: postgres:13
    alias: postgres
    command: ["postgres", "-c", "log_statement=all"]

build_joular:
  stage: build_joular
  image: maven:3.8.1-jdk-11
  script:
    - echo "Cloning JoularJX repository..."
    - git clone https://github.com/joular/joularjx.git
    - cd joularjx/
    - echo "Building JoularJX agent..."
    - mvn clean install -DskipTests

build_and_run:
  stage: build_and_run
  image: maven:3.8.1-jdk-11
  dependencies:
    - build_joular
  before_script:
    - apt-get update && apt-get install -y postgresql-client git time
    - echo "Waiting for PostgreSQL to be ready..."
    - until PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1;" &>/dev/null; do sleep 2; done
    - echo "PostgreSQL is ready!"
    - mkdir -p logs  # Ensure logs directory exists
  script:
    - echo "Building the application..."
    - mvn clean package
    - echo "Running the application with JoularJX agent..."
    - java -javaagent:/root/.m2/repository/org/noureddine/joularjx/3.0.1/joularjx-3.0.1.jar -jar target/tp4-0.0.1-SNAPSHOT.jar
